### ISSUE TITLE
Frequently getting this error

### ISSUE THREAD

**Issue by robillo** [100mslive/sample-app-android#100]
E/HMSTransport: join: failed ❌ [token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNjEyZjU1MWU2M2ExOWM4ZjI2ZGYzNWY2Iiwicm9vbV9pZCI6IjYxMzA3ZjNkZDkxNzAzZTAzNzViN2VlZiIsInVzZXJfaWQiOiI4MmFiMGI0MmM2YjkiLCJyb2xlIjoibGlzdGVuZXIiLCJ0eXBlIjoiYXBwIiwidmVyc2lvbiI6MiwiaWF0IjoxNjMxMjY2OTc1LCJuYmYiOjE2MzEyNjY5NzUsImV4cCI6MTYzMTM1MzM3NSwianRpIjoiYWE2ZDU0ZjktYTEyOS00YjI1LTlkMWItZTUzM2EzYWFjZWI4In0.x9xtSfTwt0Qk0_NUa2Vg-Gq7c4AARbuw0uA3Ed_w70A]
    ServerErrors: [JOIN]: peer is gone [code=41001, action=JOIN, description=peer is gone, cause=null]
        at live.hms.video.error.ErrorFactory$WebsocketMethodErrors.ServerErrors(ErrorFactory.kt:356)
        at live.hms.video.error.ErrorFactory$WebsocketMethodErrors.ServerErrors$default(ErrorFactory.kt:350)
        at live.hms.video.signal.jsonrpc.JSONRpcSignal.onMessage(JSONRpcSignal.kt:279)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by PratimMallick** [comment]
@robillo THis issue comes when the SDK was trying to reconnect but took long enough and finally got connected after 50sec. Our server kicks out a peer who is not connected for 50 seconds and hence this error comes up.

We have made some optimization in later builds (>2.1.4) to fix this
