### ISSUE TITLE
Crash in HMSNotifications.java

### ISSUE THREAD

**Issue by Harshal624** [100mslive/sample-app-android#208]
Crash: Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.util.Collection java.util.HashMap.values()' on a null object reference

Devices:
1. Redmi Note 10 (Android 11)
2. Samsung Galaxy J7 Prime (Android 8.1.0)

Random crash during video session 

Stack trace: 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Collection java.util.HashMap.values()' on a null object reference
       at live.hms.video.sdk.models.HMSNotifications$Peer.getTracks(HMSNotifications.java:21)
       at live.hms.video.sdk.managers.InitialPeerListManager.manage(InitialPeerListManager.java:28)
       at live.hms.video.sdk.SDKDelegate$transportObserver$1.onNotification(SDKDelegate.java:129)
       at live.hms.video.transport.HMSTransport$signalObserver$1.onNotification(HMSTransport.java:290)
       at live.hms.video.signal.jsonrpc.JSONRpcSignal$onMessage$2.invokeSuspend(JSONRpcSignal.java:361)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by AniketSK** [comment]
Hi @Harshal624 thanks for the report. Could you confirm which version of the sdk you were using when you go this crash?

**Comment by Harshal624** [comment]
2.2.3
Haven’t seen this crash since SDK version 2.3.5 though.

**Comment by AniketSK** [comment]
Thanks for confirming @Harshal624 , yes this was fixed in a previous version thanks for checking in though. Do let us know if this pops up again.
