### ISSUE TITLE
Crash in HMSVideoCapturer.java

### ISSUE THREAD

**Issue by Harshal624** [100mslive/sample-app-android#209]
Crash: Fatal Exception: java.lang.NullPointerException
create( LOCAL_CAMERA_CAPTURER_THREAD, SharedEglContext.context ) must not be null

Happens during the initialization of SurfaceViewRenderer

Device: 
1. Redmi 4 Pro (Android 7.1.2)
2. Mi 5 (Android 8.0.0)
3. Redmi 8A dual (Android 9)
4. Oneplus A5000 (Android 9)

Stack trace: Fatal Exception: java.lang.NullPointerException: create(
    LOCAL_CAMERA_CAPTURER_THREAD,
    SharedEglContext.context
  ) must not be null
       at live.hms.video.media.tracks.HMSVideoCapturer.<init>(HMSVideoCapturer.java:42)
       at live.hms.video.media.streams.HMSStreamFactory.makeLocalVideoCapturer(HMSStreamFactory.java:72)
       at live.hms.video.transport.HMSTransport.getLocalTrackByType(HMSTransport.java:805)
       at live.hms.video.sdk.SDKDelegate.initLocalTracks(SDKDelegate.java:553)
       at live.hms.video.sdk.SDKDelegate.getLocalTracksByRoleAndApplySettings(SDKDelegate.java:493)
       at live.hms.video.sdk.SDKDelegate.access$getLocalTracksByRoleAndApplySettings(SDKDelegate.java:49)
       at live.hms.video.sdk.SDKDelegate$onPolicyChangeHandled$1.invokeSuspend(SDKDelegate.java:376)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)

**Comment by AniketSK** [comment]
Hi thanks for the report @Harshal624, could you tell me the frequency of this crash? Does it always crash on that device?

**Comment by Harshal624** [comment]
I have updated the device list. It's not just one device.  
According to crashlytics: This issue has 8 crash events affecting 6 users in last 90 days.

**Comment by Harshal624** [comment]
As I said, it doesn't always crash. Most of the time the SurfaceViewRenderer init works fine without crashing. But sometimes it crashes randomly.
