### ISSUE TITLE
Crashing on Android 8 - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Harshal624** [100mslive/sample-app-android#541]
Device: Moto G Plus 
Android: 8.1.0

SDK version: 2.8.3 

Project gradle tools version: 4.2.2 

Stack trace: 
java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/FloatBuffer; in class Ljava/nio/FloatBuffer; or its super classes (declaration of 'java.nio.FloatBuffer' appears in /system/framework/core-oj.jar)
                 	at org.webrtc.GlUtil.createFloatBuffer(GlUtil.java:47)
                 	at org.webrtc.GlGenericDrawer.<clinit>(GlGenericDrawer.java:75)
                 	at org.webrtc.YuvConverter.<init>(YuvConverter.java:111)
                 	at org.webrtc.YuvConverter.<init>(YuvConverter.java:118)
                 	at org.webrtc.SurfaceTextureHelper.create(SurfaceTextureHelper.java:92)
                 	at live.hms.video.media.capturers.HMSCameraCapturer.<init>(HMSCameraCapturer.kt:48)
                 	at live.hms.video.media.streams.HMSStreamFactory.makeLocalVideoCapturer(HMSStreamFactory.kt:75)
                 	at live.hms.video.transport.HMSTransport.getLocalTrackByType(HMSTransport.kt:972)
                 	at live.hms.video.sdk.SDKDelegate.initLocalTracks(SDKDelegate.kt:790)
                 	at live.hms.video.sdk.SDKDelegate.getLocalTracksByRoleAndApplySettings(SDKDelegate.kt:716)
                 	at live.hms.video.sdk.SDKDelegate.access$getLocalTracksByRoleAndApplySettings(SDKDelegate.kt:55)
                 	at live.hms.video.sdk.SDKDelegate$onPolicyChangeHandled$1.invokeSuspend(SDKDelegate.kt:488)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                 	at java.lang.Thread.run(Thread.java:764)

**Comment by AniketSK** [comment]
hi @Harshal624 what version of gradle are you using?

**Comment by Harshal624** [comment]
> hi @Harshal624 what version of gradle are you using?

distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip

**Comment by AniketSK** [comment]
Have you set the following values in your app level build.grade?
`compileOptions {
      sourceCompatibility JavaVersion.VERSION_11
      targetCompatibility JavaVersion.VERSION_11
    }`
https://github.com/jatecl/react-native-webrtc/commit/e35a1c84e158edc5a01860e76fab022792ae481b

**Comment by AniketSK** [comment]
@Harshal624 this may help as it's a problem with lower levels of java and gradle.

> Have you set the following values in your app level build.grade? `compileOptions { sourceCompatibility JavaVersion.VERSION_11 targetCompatibility JavaVersion.VERSION_11 }` [jatecl/react-native-webrtc@e35a1c8](https://github.com/jatecl/react-native-webrtc/commit/e35a1c84e158edc5a01860e76fab022792ae481b)
