### ISSUE TITLE
Illegal Argument Exception (unreproducible)

### ISSUE THREAD

**Issue by robillo** [100mslive/sample-app-android#99]
FATAL EXCEPTION: local-camera-capturer-thread
    Process: com.kutumb.android, PID: 11120
    java.lang.IllegalArgumentException: supportsCameraApi:2095: Unknown camera ID 1
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:888)
        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:359)
        at org.webrtc.Camera2Session.start(Camera2Session.java:304)
        at org.webrtc.Camera2Session.<init>(Camera2Session.java:296)
        at org.webrtc.Camera2Session.create(Camera2Session.java:274)
        at org.webrtc.Camera2Capturer.createCameraSession(Camera2Capturer.java:35)
        at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:272)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.os.ServiceSpecificException: supportsCameraApi:2095: Unknown camera ID 1 (code 3)
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.hardware.ICameraService$Stub$Proxy.supportsCameraApi(ICameraService.java:800)
        at android.hardware.camera2.CameraManager.supportsCameraApiLocked(CameraManager.java:941)
        at android.hardware.camera2.CameraManager.supportsCamera2ApiLocked(CameraManager.java:917)
        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:307)
        at org.webrtc.Camera2Session.start(Camera2Session.java:304) 
        at org.webrtc.Camera2Session.<init>(Camera2Session.java:296) 
        at org.webrtc.Camera2Session.create(Camera2Session.java:274) 
        at org.webrtc.Camera2Capturer.createCameraSession(Camera2Capturer.java:35) 
        at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:272) 
        at android.os.Handler.handleCallback(Handler.java:914) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by PratimMallick** [comment]
@robillo When are you getting this issue, and which device this is coming on?

**Comment by robillo** [comment]
wasn't able to replicate, got this randomly (Xiaomi Redmi Note 8)
